### ISSUE TITLE
Incorrect version on pypi

### ISSUE THREAD

**Issue by hermanocabral** [charlesflynn/eve-docs#11]
Howdy,

I'm getting a weird behavior when installing Eve-docs from pypi. Both your code and pypi report the latest version as 0.1.4, but when installing I can only see up to version 0.1.2.

Here are the logs for a clean install of eve-docs:

```
HCN@ODIN /c/temp/eve-docs-test
$ virtualenv _env --no-site-packages --always-copy
New python executable in _env\Scripts\python.exe
Installing setuptools, pip...done.

HCN@ODIN /c/temp/eve-docs-test
$ source _env/Scripts/activate
(_env)
HCN@ODIN /c/temp/eve-docs-test
$ pip list
pip (1.5.4)
setuptools (2.2)
(_env)
HCN@ODIN /c/temp/eve-docs-test
$ pip install eve-docs==0.1.4
Downloading/unpacking eve-docs==0.1.4
  Could not find a version that satisfies the requirement eve-docs==0.1.4 (from versions: 0.1.0, 0.1.1, 0.1.2)
Cleaning up...
No distributions matching the version for eve-docs==0.1.4
Storing debug log for failure in ....
```

Notice the error message from pip: **Could not find a version that satisfies the requirement eve-docs==0.1.4 (from versions: 0.1.0, 0.1.1, 0.1.2)**

**Comment by charlesflynn** [comment]
Thanks for letting me know. That is really weird, PyPI had the entries for 0.1.3 and 0.1.4, but no files and no corresponding entries on the simple index. I've re-uploaded 0.1.4 and I can see it [there](https://pypi.python.org/simple/Eve-docs/) now, so give it another shot.

```
cflynn@coyote:/tmp/test$ virtualenv _env --no-site-packages --always-copy
New python executable in _env/bin/python
Installing setuptools, pip...done.
cflynn@coyote:/tmp/test$ source _env/bin/activate
_env cflynn@coyote:/tmp/test$ pip install eve-docs==0.1.4
Downloading/unpacking eve-docs==0.1.4
  Downloading Eve-docs-0.1.4.tar.gz
  Running setup.py (path:/tmp/test/_env/build/eve-docs/setup.py) egg_info for package eve-docs

Downloading/unpacking Eve>=0.1 (from eve-docs==0.1.4)
...
```

**Comment by hermanocabral** [comment]
Yep, got the latest version (0.1.4) now from pypi, looks like everything is back to normal :)

Thanks!
