### ISSUE TITLE
Add eve-docs to PyPI

### ISSUE THREAD

**Issue by joshvillbrandt** [charlesflynn/eve-docs#3]
Hey @charlesflynn, can you add eve-docs to PyPI so that I can install it from pip? I imagine this is pretty easy since you already have the `setup.py` file filled out.

Thanks!

**Comment by joshvillbrandt** [comment]
On a related note, I'm getting some dependency conflicts with eve-docs (specifically itsdangerous has a newer version that is getting installed by some other packages in my API.) It might be nice to make your dependencies minimum required versions unless you really need a specific version.

**Comment by charlesflynn** [comment]
Yikes, missed this issue, sorry for the slow response! It's now up at:
https://pypi.python.org/pypi/Eve-docs

On dependencies, I think the specific-version itsdangerous is coming from [Eve itself](https://github.com/nicolaiarocci/eve/blob/develop/requirements.txt):

```
itsdangerous==0.22
```

Eve-docs has:

```
    install_requires=[
        'Eve>=0.1',
        'Flask>=0.10',
        'Flask-Bootstrap>=3.0',
    ],
```
